import { type NextPage } from "next";
import Head from "next/head";
import {useState } from "react";
import { Input } from "~/component/Input";
import { FormGroup } from "~/component/FormGroup";
import { api } from "~/utils/api";
import { set } from "zod";
import { signIn } from "next-auth/react";
import { Button } from "~/component/Button";


const GeneratePage: NextPage = () => {

  const [form, setForm] = useState({
    prompt: "",
  });

  function updateForm(key: string) {
    return function(e: React.ChangeEvent<HTMLInputElement>){
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,  
      }));
    };
  }

  const generateCover = api.generate.generateCover.useMutation({
    onSuccess(data) {
      console.log('mutated', data)  
  },
});

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    
    generateCover.mutate({
      prompt: form.prompt,
    })
  };

  return (  
    <>
      <Head>
        <title>Album Cover Generator </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Button>Login</Button>
        <form className="flex flex-col gap-4" onSubmit={handleFormSubmit}>
        <FormGroup>
            <label>Enter Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")} ></Input>  
            
            <Button className="bg-blue-400 hover:bg-blue-500 rounded px-4 py-2">Generate</Button>
        </FormGroup>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;

